name: SentinelOne CNS Scan
 
on:
  push:
    branches: [ main ]
 
jobs:
  sentinelone-scan:
    runs-on: ubuntu-latest
    container:
      image: pingsafe/s1-shift-left-cli:0.5.4
      options: --entrypoint ""
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: Configure SentinelOne CLI
        run: >
          s1-cns-cli config
          --service-user-api-token ${{ secrets.S1_SERVICE_USER_API_TOKEN }}
          --management-console-url https://apne1-1101-nfr.sentinelone.net
          --scope-type SITE
          --scope-id 1966654988185990355
          --tag ${{ secrets.tag }}
 
      - name: Mark repo as safe for git
        run: git config --global --add safe.directory $PWD
 
      - name: Set branch variable
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
 
      - name: Run Secret Detector
        id: secret-detector
        run: >
          s1-cns-cli scan secret -d $PWD
          --publish-result
          --repo-full-name ${{ github.repository }}
          --repo-url ${{ github.server_url }}/${{ github.repository }}
          --provider GITHUB
        continue-on-error: true
 
      - name: Run IaC Scanner
        id: iac-scanner
        run: >
          s1-cns-cli scan iac -d $PWD
          --publish-result
          --repo-full-name ${{ github.repository }}
          --repo-url ${{ github.server_url }}/${{ github.repository }}
          --branch ${{ env.BRANCH }}
          --provider GITHUB
        continue-on-error: true
 
      - name: Run Vulnerability Scanner
        id: vuln-scanner
        run: s1-cns-cli scan vuln -d $PWD
        continue-on-error: true
 
      - name: Check for failures
        if: steps.secret-detector.outcome == 'failure' || steps.iac-scanner.outcome == 'failure' || steps.vuln-scanner.outcome == 'failure'
        run: exit 1
